# Generated by Django 4.2.14 on 2024-09-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="verification_code",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="verification_code_expires",
        ),
    ]
